name: Auto approve and merge PRs by dependabot
on: pull_request_target

jobs:
  autoapprove:
    name: Auto Approve a PR by dependabot
    runs-on: ubuntu-22.04
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v4.0.0
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    name: Auto merge after successful checks
    needs: autoapprove
    runs-on: ubuntu-22.04
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@v0.16.2
        if: github.actor == 'dependabot[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: dependencies
          MERGE_METHOD: rebase
