name: Lint

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  markdown:
    name: Markdown
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          config: '.markdownlint.json'
          globs: '**/*.md'
          continue-on-error: true

      - name: Comment on Pull Request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{ steps.markdown.outputs.summary }}
            })
